services:
  - type: web
    name: voice-bot
    env: python
    region: oregon
    prebuildCommand: |
      apt-get update && \
      apt-get install -y \
        espeak espeak-data libespeak1 libespeak-dev \
        ffmpeg \
        portaudio19-dev \
        libasound2-dev \
        libpulse-dev \
        python3-dev \
        build-essential \
        pkg-config && \
      ldconfig && \
      find /usr -name "libespeak.so*" -type f && \
      ln -sf /usr/lib/x86_64-linux-gnu/libespeak.so.1 /usr/lib/libespeak.so.1 2>/dev/null || true
    buildCommand: |
      pip install --upgrade pip && \
      pip install PyAudio && \
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.18