services:
  - type: web
    name: voice-bot
    env: python
    region: oregon
    prebuildCommand: |
      apt-get update && \
      apt-get install -y \
        espeak espeak-data libespeak1 libespeak-dev \
        espeak-ng espeak-ng-data \
        ffmpeg \
        portaudio19-dev \
        libasound2-dev \
        libpulse-dev \
        python3-dev \
        build-essential \
        pkg-config && \
      ldconfig
    buildCommand: |
      pip install --upgrade pip && \
      pip install PyAudio && \
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.18
      - key: LD_LIBRARY_PATH
        value: /usr/lib/x86_64-linux-gnu:/usr/lib:/lib